name: coffee_life_manager
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable: ^0.5.7
  intl: ^0.16.1
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  flutter_riverpod: ^0.11.0
  share: ^0.6.4+3
  sqflite: ^1.3.1
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.0
  freezed_annotation:
  flutter_launcher_icons: ^0.8.1
  firebase_analytics: ^6.0.2
  firebase_core: ^0.5.0+1
  admob_flutter: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner:
  freezed:
  pedantic_mono: any
  json_serializable:
  url_launcher: ^5.7.6

flutter:

  uses-material-design: true
  assets:
    - assets/coffee_bean_icon.png
    - assets/cafe_icon.png
    - assets/coffee_icon.png
    - assets/coffee-shop.jpg
    - assets/coffee.jpg
    - assets/icon/icon.png
  fonts:
    - family: AbriFatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
    - family: Charm
      fonts:
        - asset: assets/fonts/Charm-Regular.ttf


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
