name: coffee_life_manager
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  flutter_riverpod: ^0.11.0
  share: ^0.6.4+3
  sqflite: ^1.3.1
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.0
  maps_launcher: ^1.2.2+1
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner:
  freezed:
  pedantic_mono: any
  json_serializable:

# 必要なさそうならこれは消したい
#dependency_overrides:
#  analyzer: '0.39.14'

flutter:

  uses-material-design: true
